module.exports.channel = {
  SEARCH: "search",
  LOGIN: "login",
  SIGNUP: "signup",

  ADD_PEOPLE: "add:people",
  GET_PEOPLES: "get:peoples",
  DELETE_PEOPLE: "DELETE:people",
  EDIT_PEOPLE: "Edit:people",
  INFO_PEOPLE: "INFO:people",

  INFO_CLUBS: "INFO:clubs",
  ADD_CLUB: "add:club",
  GET_CLUBS: "get:clubs",
  DELETE_CLUB: "DELETE:club",
  EDIT_CLUB: "Edit:clubs",
  ADD_ClUBMEMBER: "add:clubMember",
  DELETE_ClUBMEMBER: "DELETE:clubMember",

  ADD_DISCIPLINE: 'add:disciplineDB',
  GET_DISCIPLINES: 'get:disciplineDBs',
  DELETE_DISCIPLINE: "DELETE:disciplineDB",
  EDIT_DISCIPLINE: "Edit:disciplineDB",
  ADD_FINAL: 'add:final',
  ADD_onRegular: 'add:onRegular',
  ADD_onElectronic: 'add:onElectronic',
  ADD_onMigratory: 'add:onMigratory',
  ADD_other: 'add:other',
  DELETE_other: 'delete:other',


  ADD_SHOOTINGRANGE: 'add:shootingrange',
  GET_SHOOTINGRANGES: 'get:shootingranges',
  DELETE_SHOOTINGRANGE: "DELETE:shootingrange",
  EDIT_SHOOTINGRANGE: "Edit:shootingrange",
  ADD_PLACESHOOTINGRANGE: 'add:placeshootingrange',
  DELETE_PLACESHOOTINGRANGES: 'DELETE:placeshootingranges',
  ADD_MANAGERSHOOTINGRANGE: "add:managershootingrange",
  DELETE_MANAGERSHOOTINGRANGE: "DELETE:managershootingrange",
  ADD_OTHERSHOOTINGRANGE: "add:othershootingrange",
  DELETE_OTHERSHOOTINGRANGE: "DELETE:othershootingrange",

  ADD_COMPETITION: 'add:compitition',
  GET_COMPETITIONS: 'get:compititions',
  DELETE_COMPETITION: "DELETE:compitition",
  EDIT_COMPETITION: "Edit:compitition",
  ADD_COMPETITIONshootingRanges: 'add:compititionshootingRanges',
  DELETE_COMPETITIONshootingRanges: "DELETE:compititionshootingRanges",
  ADD_COMPETITIONdiscipliness: 'add:compititiondisciplines',
  DELETE_COMPETITIONdisciplines: "DELETE:compititiondisciplines",
  ADD_COMPETITIONshooters: 'add:compititionshooters',
  DELETE_COMPETITIONshooters: "DELETE:compititionshooters",
  ADD_COMPETITIONstaff: 'add:compititionstaff',
  DELETE_COMPETITIONstaff: "DELETE:compititionstaff",
  ADD_COMPETITIONstaffrefrees: 'add:compititionstaffrefrees',
  DELETE_COMPETITIONstaffrefrees: "DELETE:compititionstaffrefrees",
  ADD_COMPETITIONstaffotherStaff: 'add:compititionstaffotherStaff',
  DELETE_COMPETITIONstaffotherStaff: "DELETE:compititionstaffotherStaff",
  ADD_COMPETITIONshiftRefrees: 'add:compititionshiftRefreess',
  DELETE_COMPETITIONshiftRefrees: "DELETE:compititionshiftRefrees",
  ADD_shiftsdisciplines: 'add:shiftisciplines',
  DELETE_shiftsdisciplines: "DELETE:shiftsdisciplines",
  ADD_COMPETITIONshifts: 'add:compititionshifts',
  DELETE_COMPETITIONshifts: "DELETE:compititionshifts",
  ADD_COMPETITIONshootingSessions: 'add:compititionshootingSessions',
  DELETE_COMPETITIONshootingSessions: "DELETE:compititionshootingSessions",
  INFO_COMP: "INFO:COMP",
  EDIT_RESULT: "EDIT:RESULT",
};
